// generated by goxsd; DO NOT EDIT

package mzid

import "time"

// MzIDentML is generated from an XSD element
type MzIDentML struct {
	ID                         string                     `xml:"id,attr"`
	Name                       string                     `xml:"name,attr"`
	CreationDate               time.Time                  `xml:"creationDate,attr"`
	Version                    string                     `xml:"version,attr"`
	CvList                     cvList                     `xml:"cvList"`
	AnalysisSoftwareList       AnalysisSoftwareList       `xml:"AnalysisSoftwareList"`
	Provider                   Provider                   `xml:"Provider"`
	AuditCollection            AuditCollection            `xml:"AuditCollection"`
	AnalysisSampleCollection   AnalysisSampleCollection   `xml:"AnalysisSampleCollection"`
	SequenceCollection         SequenceCollection         `xml:"SequenceCollection"`
	AnalysisCollection         AnalysisCollection         `xml:"AnalysisCollection"`
	AnalysisProtocolCollection AnalysisProtocolCollection `xml:"AnalysisProtocolCollection"`
	DataCollection             DataCollection             `xml:"DataCollection"`
	BibliographicReference     []BibliographicReference   `xml:"BibliographicReference"`
}

// cvList is generated from an XSD element
type cvList struct {
	Cv []cv `xml:"cv"`
}

// cv is generated from an XSD element
type cv struct {
	FullName string `xml:"fullName,attr"`
	Version  string `xml:"version,attr"`
	URI      string `xml:"uri,attr"`
	ID       string `xml:"id,attr"`
}

// AnalysisSoftwareList is generated from an XSD element
type AnalysisSoftwareList struct {
	AnalysisSoftware []AnalysisSoftware `xml:"AnalysisSoftware"`
}

// AnalysisSoftware is generated from an XSD element
type AnalysisSoftware struct {
	ID             string       `xml:"id,attr"`
	Name           string       `xml:"name,attr"`
	Version        string       `xml:"version,attr"`
	URI            string       `xml:"uri,attr"`
	ContactRole    ContactRole  `xml:"ContactRole"`
	SoftwareName   SoftwareName `xml:"SoftwareName"`
	Customizations string       `xml:"Customizations"`
}

// ContactRole is generated from an XSD element
type ContactRole struct {
	Contact_ref string `xml:"contact_ref,attr"`
	Role        Role   `xml:"Role"`
}

// Role is generated from an XSD element
type Role struct {
	CvParam cvParam `xml:"cvParam"`
}

// cvParam is generated from an XSD element
type cvParam struct {
	Name          string `xml:"name,attr"`
	Value         string `xml:"value,attr"`
	UnitAccession string `xml:"unitAccession,attr"`
	UnitName      string `xml:"unitName,attr"`
	UnitCvRef     string `xml:"unitCvRef,attr"`
	CvRef         string `xml:"cvRef,attr"`
	Accession     string `xml:"accession,attr"`
}

// SoftwareName is generated from an XSD element
type SoftwareName struct {
}

// Provider is generated from an XSD element
type Provider struct {
	ID                   string      `xml:"id,attr"`
	Name                 string      `xml:"name,attr"`
	AnalysisSoftware_ref string      `xml:"analysisSoftware_ref,attr"`
	ContactRole          ContactRole `xml:"ContactRole"`
}

// AuditCollection is generated from an XSD element
type AuditCollection struct {
}

// AnalysisSampleCollection is generated from an XSD element
type AnalysisSampleCollection struct {
	Sample []Sample `xml:"Sample"`
}

// Sample is generated from an XSD element
type Sample struct {
	ID          string        `xml:"id,attr"`
	Name        string        `xml:"name,attr"`
	ContactRole []ContactRole `xml:"ContactRole"`
	SubSample   []SubSample   `xml:"SubSample"`
}

// SubSample is generated from an XSD element
type SubSample struct {
	Sample_ref string `xml:"sample_ref,attr"`
}

// SequenceCollection is generated from an XSD element
type SequenceCollection struct {
	DBSequence      []DBSequence      `xml:"DBSequence"`
	Peptide         []Peptide         `xml:"Peptide"`
	PeptideEvidence []PeptideEvidence `xml:"PeptideEvidence"`
}

// DBSequence is generated from an XSD element
type DBSequence struct {
	ID                 string `xml:"id,attr"`
	Name               string `xml:"name,attr"`
	Length             int    `xml:"length,attr"`
	SearchDatabase_ref string `xml:"searchDatabase_ref,attr"`
	Accession          string `xml:"accession,attr"`
	Seq                string `xml:"Seq"`
}

// Peptide is generated from an XSD element
type Peptide struct {
	ID                       string                     `xml:"id,attr"`
	Name                     string                     `xml:"name,attr"`
	PeptideSequence          string                     `xml:"PeptideSequence"`
	Modification             []Modification             `xml:"Modification"`
	SubstitutionModification []SubstitutionModification `xml:"SubstitutionModification"`
}

// Modification is generated from an XSD element
type Modification struct {
	Location              int `xml:"location,attr"`
	Residues              `xml:"residues,attr"`
	AvgMassDelta          double    `xml:"avgMassDelta,attr"`
	MonoisotopicMassDelta double    `xml:"monoisotopicMassDelta,attr"`
	CvParam               []cvParam `xml:"cvParam"`
}

// SubstitutionModification is generated from an XSD element
type SubstitutionModification struct {
	OriginalResidue       `xml:"originalResidue,attr"`
	ReplacementResidue    `xml:"replacementResidue,attr"`
	Location              int    `xml:"location,attr"`
	AvgMassDelta          double `xml:"avgMassDelta,attr"`
	MonoisotopicMassDelta double `xml:"monoisotopicMassDelta,attr"`
}

// PeptideEvidence is generated from an XSD element
type PeptideEvidence struct {
	ID                   string `xml:"id,attr"`
	Name                 string `xml:"name,attr"`
	DBSequence_ref       string `xml:"dBSequence_ref,attr"`
	Peptide_ref          string `xml:"peptide_ref,attr"`
	Start                int    `xml:"start,attr"`
	End                  int    `xml:"end,attr"`
	Pre                  `xml:"pre,attr"`
	Post                 `xml:"post,attr"`
	TranslationTable_ref string `xml:"translationTable_ref,attr"`
	Frame                int    `xml:"frame,attr"`
	IsDecoy              bool   `xml:"isDecoy,attr"`
}

// AnalysisCollection is generated from an XSD element
type AnalysisCollection struct {
	SpectrumIDentification []SpectrumIDentification `xml:"SpectrumIdentification"`
	ProteinDetection       ProteinDetection         `xml:"ProteinDetection"`
}

// SpectrumIDentification is generated from an XSD element
type SpectrumIDentification struct {
	ID                                 string              `xml:"id,attr"`
	Name                               string              `xml:"name,attr"`
	ActivityDate                       time.Time           `xml:"activityDate,attr"`
	SpectrumIDentificationProtocol_ref string              `xml:"spectrumIdentificationProtocol_ref,attr"`
	SpectrumIDentificationList_ref     string              `xml:"spectrumIdentificationList_ref,attr"`
	InputSpectra                       []InputSpectra      `xml:"InputSpectra"`
	SearchDatabaseRef                  []SearchDatabaseRef `xml:"SearchDatabaseRef"`
}

// InputSpectra is generated from an XSD element
type InputSpectra struct {
	SpectraData_ref string `xml:"spectraData_ref,attr"`
}

// SearchDatabaseRef is generated from an XSD element
type SearchDatabaseRef struct {
	SearchDatabase_ref string `xml:"searchDatabase_ref,attr"`
}

// ProteinDetection is generated from an XSD element
type ProteinDetection struct {
	ID                           string                         `xml:"id,attr"`
	Name                         string                         `xml:"name,attr"`
	ActivityDate                 time.Time                      `xml:"activityDate,attr"`
	ProteinDetectionList_ref     string                         `xml:"proteinDetectionList_ref,attr"`
	ProteinDetectionProtocol_ref string                         `xml:"proteinDetectionProtocol_ref,attr"`
	InputSpectrumIDentifications []InputSpectrumIDentifications `xml:"InputSpectrumIdentifications"`
}

// InputSpectrumIDentifications is generated from an XSD element
type InputSpectrumIDentifications struct {
	SpectrumIDentificationList_ref string `xml:"spectrumIdentificationList_ref,attr"`
}

// AnalysisProtocolCollection is generated from an XSD element
type AnalysisProtocolCollection struct {
	SpectrumIDentificationProtocol []SpectrumIDentificationProtocol `xml:"SpectrumIdentificationProtocol"`
	ProteinDetectionProtocol       ProteinDetectionProtocol         `xml:"ProteinDetectionProtocol"`
}

// SpectrumIDentificationProtocol is generated from an XSD element
type SpectrumIDentificationProtocol struct {
	ID                     string                 `xml:"id,attr"`
	Name                   string                 `xml:"name,attr"`
	AnalysisSoftware_ref   string                 `xml:"analysisSoftware_ref,attr"`
	SearchType             SearchType             `xml:"SearchType"`
	AdditionalSearchParams AdditionalSearchParams `xml:"AdditionalSearchParams"`
	ModificationParams     ModificationParams     `xml:"ModificationParams"`
	Enzymes                Enzymes                `xml:"Enzymes"`
	MassTable              []MassTable            `xml:"MassTable"`
	FragmentTolerance      FragmentTolerance      `xml:"FragmentTolerance"`
	ParentTolerance        ParentTolerance        `xml:"ParentTolerance"`
	Threshold              Threshold              `xml:"Threshold"`
	DatabaseFilters        DatabaseFilters        `xml:"DatabaseFilters"`
	DatabaseTranslation    DatabaseTranslation    `xml:"DatabaseTranslation"`
}

// SearchType is generated from an XSD element
type SearchType struct {
}

// AdditionalSearchParams is generated from an XSD element
type AdditionalSearchParams struct {
}

// ModificationParams is generated from an XSD element
type ModificationParams struct {
	SearchModification []SearchModification `xml:"SearchModification"`
}

// SearchModification is generated from an XSD element
type SearchModification struct {
	FixedMod         bool  `xml:"fixedMod,attr"`
	MassDelta        float `xml:"massDelta,attr"`
	Residues         `xml:"residues,attr"`
	SpecificityRules []SpecificityRules `xml:"SpecificityRules"`
	CvParam          []cvParam          `xml:"cvParam"`
}

// SpecificityRules is generated from an XSD element
type SpecificityRules struct {
	CvParam []cvParam `xml:"cvParam"`
}

// Enzymes is generated from an XSD element
type Enzymes struct {
	Independent bool     `xml:"independent,attr"`
	Enzyme      []Enzyme `xml:"Enzyme"`
}

// Enzyme is generated from an XSD element
type Enzyme struct {
	ID              string `xml:"id,attr"`
	Name            string `xml:"name,attr"`
	NTermGain       `xml:"nTermGain,attr"`
	CTermGain       `xml:"cTermGain,attr"`
	SemiSpecific    bool `xml:"semiSpecific,attr"`
	MissedCleavages int  `xml:"missedCleavages,attr"`
	MinDistance     `xml:"minDistance,attr"`
	SiteRegexp      string     `xml:"SiteRegexp"`
	EnzymeName      EnzymeName `xml:"EnzymeName"`
}

// EnzymeName is generated from an XSD element
type EnzymeName struct {
}

// MassTable is generated from an XSD element
type MassTable struct {
	ID               string `xml:"id,attr"`
	Name             string `xml:"name,attr"`
	MsLevel          `xml:"msLevel,attr"`
	Residue          []Residue          `xml:"Residue"`
	AmbiguousResidue []AmbiguousResidue `xml:"AmbiguousResidue"`
}

// Residue is generated from an XSD element
type Residue struct {
	Code string `xml:"code,attr"`
	Mass float  `xml:"mass,attr"`
}

// AmbiguousResidue is generated from an XSD element
type AmbiguousResidue struct {
	Code string `xml:"code,attr"`
}

// FragmentTolerance is generated from an XSD element
type FragmentTolerance struct {
	CvParam []cvParam `xml:"cvParam"`
}

// ParentTolerance is generated from an XSD element
type ParentTolerance struct {
	CvParam []cvParam `xml:"cvParam"`
}

// Threshold is generated from an XSD element
type Threshold struct {
}

// DatabaseFilters is generated from an XSD element
type DatabaseFilters struct {
	Filter []Filter `xml:"Filter"`
}

// Filter is generated from an XSD element
type Filter struct {
	FilterType FilterType `xml:"FilterType"`
	Include    Include    `xml:"Include"`
	Exclude    Exclude    `xml:"Exclude"`
}

// FilterType is generated from an XSD element
type FilterType struct {
}

// Include is generated from an XSD element
type Include struct {
}

// Exclude is generated from an XSD element
type Exclude struct {
}

// DatabaseTranslation is generated from an XSD element
type DatabaseTranslation struct {
	Frames           `xml:"frames,attr"`
	TranslationTable []TranslationTable `xml:"TranslationTable"`
}

// TranslationTable is generated from an XSD element
type TranslationTable struct {
	ID      string    `xml:"id,attr"`
	Name    string    `xml:"name,attr"`
	CvParam []cvParam `xml:"cvParam"`
}

// ProteinDetectionProtocol is generated from an XSD element
type ProteinDetectionProtocol struct {
	ID                   string         `xml:"id,attr"`
	Name                 string         `xml:"name,attr"`
	AnalysisSoftware_ref string         `xml:"analysisSoftware_ref,attr"`
	AnalysisParams       AnalysisParams `xml:"AnalysisParams"`
	Threshold            Threshold      `xml:"Threshold"`
}

// AnalysisParams is generated from an XSD element
type AnalysisParams struct {
}

// DataCollection is generated from an XSD element
type DataCollection struct {
	Inputs       Inputs       `xml:"Inputs"`
	AnalysisData AnalysisData `xml:"AnalysisData"`
}

// Inputs is generated from an XSD element
type Inputs struct {
	SourceFile     []SourceFile     `xml:"SourceFile"`
	SearchDatabase []SearchDatabase `xml:"SearchDatabase"`
	SpectraData    []SpectraData    `xml:"SpectraData"`
}

// SourceFile is generated from an XSD element
type SourceFile struct {
	ID                          string     `xml:"id,attr"`
	Name                        string     `xml:"name,attr"`
	Location                    string     `xml:"location,attr"`
	ExternalFormatDocumentation string     `xml:"ExternalFormatDocumentation"`
	FileFormat                  FileFormat `xml:"FileFormat"`
}

// FileFormat is generated from an XSD element
type FileFormat struct {
	CvParam cvParam `xml:"cvParam"`
}

// SearchDatabase is generated from an XSD element
type SearchDatabase struct {
	ID                          string       `xml:"id,attr"`
	Name                        string       `xml:"name,attr"`
	Location                    string       `xml:"location,attr"`
	Version                     string       `xml:"version,attr"`
	ReleaseDate                 time.Time    `xml:"releaseDate,attr"`
	NumDatabaseSequences        int          `xml:"numDatabaseSequences,attr"`
	NumResidues                 int          `xml:"numResidues,attr"`
	ExternalFormatDocumentation string       `xml:"ExternalFormatDocumentation"`
	FileFormat                  FileFormat   `xml:"FileFormat"`
	DatabaseName                DatabaseName `xml:"DatabaseName"`
	CvParam                     []cvParam    `xml:"cvParam"`
}

// DatabaseName is generated from an XSD element
type DatabaseName struct {
}

// SpectraData is generated from an XSD element
type SpectraData struct {
	ID                          string           `xml:"id,attr"`
	Name                        string           `xml:"name,attr"`
	Location                    string           `xml:"location,attr"`
	ExternalFormatDocumentation string           `xml:"ExternalFormatDocumentation"`
	FileFormat                  FileFormat       `xml:"FileFormat"`
	SpectrumIDFormat            SpectrumIDFormat `xml:"SpectrumIDFormat"`
}

// SpectrumIDFormat is generated from an XSD element
type SpectrumIDFormat struct {
	CvParam cvParam `xml:"cvParam"`
}

// AnalysisData is generated from an XSD element
type AnalysisData struct {
	SpectrumIDentificationList []SpectrumIDentificationList `xml:"SpectrumIdentificationList"`
	ProteinDetectionList       ProteinDetectionList         `xml:"ProteinDetectionList"`
}

// SpectrumIDentificationList is generated from an XSD element
type SpectrumIDentificationList struct {
	ID                           string                         `xml:"id,attr"`
	Name                         string                         `xml:"name,attr"`
	NumSequencesSearched         int                            `xml:"numSequencesSearched,attr"`
	FragmentationTable           FragmentationTable             `xml:"FragmentationTable"`
	SpectrumIDentificationResult []SpectrumIDentificationResult `xml:"SpectrumIdentificationResult"`
}

// FragmentationTable is generated from an XSD element
type FragmentationTable struct {
	Measure []Measure `xml:"Measure"`
}

// Measure is generated from an XSD element
type Measure struct {
	ID      string    `xml:"id,attr"`
	Name    string    `xml:"name,attr"`
	CvParam []cvParam `xml:"cvParam"`
}

// SpectrumIDentificationResult is generated from an XSD element
type SpectrumIDentificationResult struct {
	ID                         string                       `xml:"id,attr"`
	Name                       string                       `xml:"name,attr"`
	SpectrumID                 string                       `xml:"spectrumID,attr"`
	SpectraData_ref            string                       `xml:"spectraData_ref,attr"`
	SpectrumIDentificationItem []SpectrumIDentificationItem `xml:"SpectrumIdentificationItem"`
}

// SpectrumIDentificationItem is generated from an XSD element
type SpectrumIDentificationItem struct {
	ID                       string               `xml:"id,attr"`
	Name                     string               `xml:"name,attr"`
	ChargeState              int                  `xml:"chargeState,attr"`
	ExperimentalMassToCharge double               `xml:"experimentalMassToCharge,attr"`
	CalculatedMassToCharge   double               `xml:"calculatedMassToCharge,attr"`
	CalculatedPI             float                `xml:"calculatedPI,attr"`
	Peptide_ref              string               `xml:"peptide_ref,attr"`
	Rank                     int                  `xml:"rank,attr"`
	PassThreshold            bool                 `xml:"passThreshold,attr"`
	MassTable_ref            string               `xml:"massTable_ref,attr"`
	Sample_ref               string               `xml:"sample_ref,attr"`
	PeptideEvidenceRef       []PeptideEvidenceRef `xml:"PeptideEvidenceRef"`
	Fragmentation            Fragmentation        `xml:"Fragmentation"`
}

// PeptideEvidenceRef is generated from an XSD element
type PeptideEvidenceRef struct {
	PeptideEvidence_ref string `xml:"peptideEvidence_ref,attr"`
}

// Fragmentation is generated from an XSD element
type Fragmentation struct {
	IonType []IonType `xml:"IonType"`
}

// IonType is generated from an XSD element
type IonType struct {
	Index         `xml:"index,attr"`
	Charge        int             `xml:"charge,attr"`
	FragmentArray []FragmentArray `xml:"FragmentArray"`
	UserParam     []userParam     `xml:"userParam"`
	CvParam       []cvParam       `xml:"cvParam"`
}

// FragmentArray is generated from an XSD element
type FragmentArray struct {
	Values      `xml:"values,attr"`
	Measure_ref string `xml:"measure_ref,attr"`
}

// userParam is generated from an XSD element
type userParam struct {
	Name          string `xml:"name,attr"`
	Value         string `xml:"value,attr"`
	UnitAccession string `xml:"unitAccession,attr"`
	UnitName      string `xml:"unitName,attr"`
	UnitCvRef     string `xml:"unitCvRef,attr"`
	Type          string `xml:"type,attr"`
}

// ProteinDetectionList is generated from an XSD element
type ProteinDetectionList struct {
	ID                    string                  `xml:"id,attr"`
	Name                  string                  `xml:"name,attr"`
	ProteinAmbiguityGroup []ProteinAmbiguityGroup `xml:"ProteinAmbiguityGroup"`
}

// ProteinAmbiguityGroup is generated from an XSD element
type ProteinAmbiguityGroup struct {
	ID                         string                       `xml:"id,attr"`
	Name                       string                       `xml:"name,attr"`
	ProteinDetectionHypothesis []ProteinDetectionHypothesis `xml:"ProteinDetectionHypothesis"`
}

// ProteinDetectionHypothesis is generated from an XSD element
type ProteinDetectionHypothesis struct {
	ID                string              `xml:"id,attr"`
	Name              string              `xml:"name,attr"`
	DBSequence_ref    string              `xml:"dBSequence_ref,attr"`
	PassThreshold     bool                `xml:"passThreshold,attr"`
	PeptideHypothesis []PeptideHypothesis `xml:"PeptideHypothesis"`
}

// PeptideHypothesis is generated from an XSD element
type PeptideHypothesis struct {
	PeptideEvidence_ref           string                          `xml:"peptideEvidence_ref,attr"`
	SpectrumIDentificationItemRef []SpectrumIDentificationItemRef `xml:"SpectrumIdentificationItemRef"`
}

// SpectrumIDentificationItemRef is generated from an XSD element
type SpectrumIDentificationItemRef struct {
	SpectrumIDentificationItem_ref string `xml:"spectrumIdentificationItem_ref,attr"`
}

// BibliographicReference is generated from an XSD element
type BibliographicReference struct {
	ID          string `xml:"id,attr"`
	Name        string `xml:"name,attr"`
	Authors     string `xml:"authors,attr"`
	Publication string `xml:"publication,attr"`
	Publisher   string `xml:"publisher,attr"`
	Editor      string `xml:"editor,attr"`
	Year        int    `xml:"year,attr"`
	Volume      string `xml:"volume,attr"`
	Issue       string `xml:"issue,attr"`
	Pages       string `xml:"pages,attr"`
	Title       string `xml:"title,attr"`
	Doi         string `xml:"doi,attr"`
}
